services:
  - type: web
    name: my-node-app
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: MONGODB_URI
        value: "mongodb+srv://Vinit04:DGFSFM15xAbnOvjV@cluster0.mongodb.net/AppleDB?retryWrites=true&w=majority"